# Generated by Django 3.0 on 2021-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ISBN',
            field=models.IntegerField(default=0),
        ),
    ]
