# Generated by Django 3.0 on 2021-05-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
