# Generated by Django 3.0 on 2021-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ISBN',
            new_name='Isbn',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
