# Generated by Django 3.0 on 2021-05-13 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210513_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Returndate',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
